services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${PGHOST}
      DATABASE_PORT: ${PGPORT}
      DATABASE_USER: ${PGUSER}
      DATABASE_PASSWORD: ${PGPASSWORD}
      DATABASE_NAME: ${PGDATABASE}
    restart: always